%{
***********************************************************************
**************         3D Printing Research Group        **************
***********************************************************************
************            Principal Invetigator (PI):        ************
*********               >>>   Dr. Yiwei Weng   <<<            *********
***********************************************************************
***               The Hong Kong Polytechnic University             ****
***              Department of Building and Real Estate            ****
***                         Hong Kong (PRC)                        ****
***********************************************************************
*---------------------------------------------------------------------*
*                 Lab Website: wengyiwei.github.io                    *
*---------------------------------------------------------------------*
*                                                                     *
***********************************************************************
****        Class for the Bacis Calculation in Robot Arm           ****
***********************************************************************
*---------------------------------------------------------------------*
*                   Start date:    Augest 04 2024                     *
*                   Last update:   Augest 04 2024                     *
*---------------------------------------------------------------------*
*                                                                     *
***********************************************************************
_______________________________________________________________________

                                                          Copyright (C)
                                                           2024-present
                                                            by LIU Tong
                                                              Hong Kong
                                             People's Republic of China
_______________________________________________________________________
%}
classdef PathInfill
  %{
***********************************************************************
  Summary of the Class:
  This calss is created to generate infill path 
  
***********************************************************************
* Properties:                                                         *
*                                                                     *
*  none                                                               *
*                                                                     *
* Methods(Static)                                                     *
*                                                                     *
    PathInfill.hilbert  --- To generate hilbert infill path in a 
                             square zone
*_____________________________________________________________________*
*

*---------------------------------------------------------------------*
  %}
    

    
    methods(Static)


        
    function [x,y] = hilbert(n)
% [X,Y] = HILBERT(N) calculates and returns the co-ordinates of
% the nodes of the n-th iteration of Hilbert's space-filling curve
% using recursion.
% It also draws the curve at the n-th iteration.
% [X,Y] = HILBERT uses N = 4.
% This file was generated by students as a partial fulfillment
% for the requirements of the course "Fractals", Winter term
% 2004/2005, Stuttgart University.
% Author : Melanie Reichner, Jonas Offtermatt
% Date   : Nov 2004
% Version: 1.0
%default setting
 Recursive = @ PathInfill.hilbert ;
if nargin ~= 1
    n = 4;
end
% end of recursion
if n <= 0
  x = 0;
  y = 0;
 
%recursive method call
else
  [x0,y0] = Recursive(n-1);
 
  %calculate new co-ordinates
  wid = 0.5 ;
  
  x = wid*[-wid+y0 -wid+x0 wid+x0 wid-y0];
  y = wid*[-wid+x0 wid+y0 wid+y0 -wid-x0];
end
end
    end
end

